name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Chekout repository
      uses: actions/checkout@v2
      
    - name: install dependencies
      run: sudo apt-get install -y g++
      
    - name: Compile C++ code
      run: g++ -o main nugas-1.cpp
      
    - name: Run the program
      run: ./main
